# Generated by Django 4.2 on 2024-12-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="店铺名称")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("address", models.CharField(max_length=200, verbose_name="地址")),
                ("tags", models.CharField(max_length=100, verbose_name="标签")),
                ("rating", models.FloatField(default=0.0, verbose_name="评分")),
            ],
        ),
    ]
